version: "3.8"
services:
  api:
    container_name: api
    networks:
      - my-network

    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
    - "5000:83"
  
  client:
    container_name: client
    networks:
      - my-network
    build:
    
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5001:4200"
networks:
  my-network:
